// TODO GET ACTIONS
export const GET_TODO_REQUEST = "GET_TODO_REQUEST"
export const GET_TODO_SUCCESS = "GET_TODO_SUCCESS"
export const GET_TODO_FAILURE = "GET_TODO_FAILURE"

// TODO POST ACTIONS
export const POST_TODO_REQUEST = "POST_TODO_REQUEST"
export const POST_TODO_SUCCESS = "POST_TODO_SUCCESS"
export const POST_TODO_FAILURE = "POST_TODO_FAILURE"

// TODO UPDATE ACTIONS
export const UPDATE_TODO_REQUEST = "UPDATE_TODO_REQUEST"
export const UPDATE_TODO_SUCCESS = "UPDATE_TODO_SUCCESS"
export const UPDATE_TODO_FAILURE = "UPDATE_TODO_FAILURE"

// TODO DELETE ACTION
export const DELETE_TODO_REQUEST = "DELETE_TODO_REQUEST"
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS"
export const DELETE_TODO_FAILURE = "DELETE_TODO_FAILURE"

